name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépôt courant
        uses: actions/checkout@v4

      - name: Configuration Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Analyse SonarCloud avec Maven
        run: mvn -B verify org.sonarsource.scanner.maven:sonar \
          -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
